vim.pack.add({
  { src = "https://github.com/MagicDuck/grug-far.nvim",          lazy = true },
  { src = "https://github.com/MunifTanjim/nui.nvim",             lazy = true },
  { src = "https://github.com/NvChad/nvim-colorizer.lua",        lazy = true },
  { src = "https://github.com/RRethy/vim-illuminate",            lazy = true },
  { src = "https://github.com/chomosuke/typst-preview.nvim",     lazy = true },
  { src = "https://github.com/christoomey/vim-tmux-navigator",   lazy = false },
  { src = "https://github.com/echasnovski/mini.icons",           lazy = true },
  { src = "https://github.com/echasnovski/mini.indentscope",     lazy = true },
  { src = "https://github.com/echasnovski/mini.pairs",           lazy = true },
  { src = "https://github.com/echasnovski/mini.statusline",      lazy = true },
  { src = "https://github.com/echasnovski/mini.surround",        lazy = true },
  { src = "https://github.com/folke/snacks.nvim",                lazy = false },
  { src = "https://github.com/folke/tokyonight.nvim",            lazy = false },
  { src = "https://github.com/echasnovski/mini.comment",         lazy = true },
  { src = "https://github.com/lewis6991/gitsigns.nvim",          lazy = false },
  { src = "https://github.com/nvim-lua/plenary.nvim",            lazy = true },
  { src = "https://github.com/nvim-tree/nvim-web-devicons",      lazy = true },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter",  lazy = false },
  { src = "https://github.com/saghen/blink.cmp",                 lazy = true },
  { src = "https://github.com/tpope/vim-fugitive",               lazy = false },
  { src = "https://github.com/tpope/vim-rhubarb",                lazy = false },
  { src = "https://github.com/tpope/vim-sleuth",                 lazy = false },
  { src = "https://github.com/vim-utils/vim-most-minimal-folds", lazy = false },
  { src = "https://github.com/xiyaowong/virtcolumn.nvim",        lazy = false },
  { src = "https://github.com/ysmb-wtsg/in-and-out.nvim",        lazy = false },
})
